# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/edit_dir_name_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditDirNameDialog(object):
    def setupUi(self, EditDirNameDialog):
        EditDirNameDialog.setObjectName("EditDirNameDialog")
        EditDirNameDialog.resize(400, 120)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditDirNameDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EditDirNameDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_new_name = QtWidgets.QLineEdit(EditDirNameDialog)
        self.lineEdit_new_name.setObjectName("lineEdit_new_name")
        self.verticalLayout.addWidget(self.lineEdit_new_name)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditDirNameDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditDirNameDialog)
        self.buttonBox.accepted.connect(EditDirNameDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EditDirNameDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditDirNameDialog)

    def retranslateUi(self, EditDirNameDialog):
        _translate = QtCore.QCoreApplication.translate
        EditDirNameDialog.setWindowTitle(_translate("EditDirNameDialog", "Verzeichnis umbenennen"))
        self.label.setText(_translate("EditDirNameDialog", "Neuer Verzeichnisname:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditDirNameDialog = QtWidgets.QDialog()
    ui = Ui_EditDirNameDialog()
    ui.setupUi(EditDirNameDialog)
    EditDirNameDialog.show()
    sys.exit(app.exec_())
